#!/bin/bash

# Broker's' command line client. Used as an alternative
# to the Web UI

function add() {
    read -p "Name: " USER
    read -p "Commmand:" COMMAND
    read -p "Description:" DESCRIPTION

    curl -H "Content-Type: application/json" \
    -d '{"user":"'$USER'","description":"'"$DESCRIPTION"'","command":"'"$COMMAND"'"}' \
    localhost:5000/jobs
}


function list() {
    curl localhost:5000/jobs | python -m json.tool 
}

function remove() {
    curl -X DELETE localhost:5000/jobs/$1
}


if [[ $1 == "add" ]]; then 
    add 
elif [[ $1 == "list" ]]; then
    list
elif [[ $1 == "remove" ]]; then
    remove $2
elif [[ $1 == "help" ]]; then
    echo "To add a new job: broker add"
    echo "To show all jobs: broker list"
    echo "To remove a job: broker remove [id]"
fi
