name: CI Pipeline

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.3
      - name: Install dependencies
        run: export PATH=~/.poetry/bin/:$PATH && poetry -h
#       - name: pylint3-action
#         uses: LakshitF/pylint3-action@v2
#         with:
#           filename: broker *.py
